version: '3'
services:
  web_app:
    build:
      context: .
      dockerfile: dockerfile
    networks:
      keycloak_net:
        ipv4_address: 10.5.0.2
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    command: ["start-dev", "--import-realm"]
    restart: unless-stopped
    networks:
      keycloak_net:
        ipv4_address: 10.5.0.3
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - ./data:/opt/jboss/keycloak/data

networks:
  keycloak_net:
    name: priv_network
    external: true